version: '3'
networks:
  ros:
    driver: bridge
services:
  ros-master:
    image: ros-noetic:base
    hostname: ros-master
    command: roscore
    networks:
      - ros
    restart: always

  jkl:
    image: dense-fusion-ros:wander
    hostname: jkl-server
    container_name: jkl
    depends_on:
      - ros-master
    environment:
      - "ROS_HOSTNAME=pcl_publisher"
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_DOMAIN_ID=100"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    user: "1000:1000"
    volumes:
      - "/home/$USER:/home/$USER"
      - "/etc/group:/etc/group:ro"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/shadow:/etc/shadow:ro"
      - "/etc/sudoers.d:/etc/sudoers.d:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    working_dir: "/home/$USER/kusumoto/dense-fusion-ros/catkin_ws/"
    networks:
      - ros
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
            
  asdf:
    image: dense-fusion-ros:wander
    hostname: asdf-server
    container_name: asdf
    environment:
      - "ROS_HOSTNAME=pcl_subscriber"
      - "ROS_DOMAIN_ID=100"
      - "ROS_MASTER_URI=http://ros-master:11311"
    # command:
    #   - source /opt/ros/foxy/setup.bash
    #   - . install/local_setup.bash
    #   - ros2 run pcl_publisher wander_pcl_sub
    volumes:
      - "/home/$USER/kusumoto/dense-fusion-ros/catkin_ws/:/root/catkin_ws/"
    networks:
      - ros
    tty: true
    restart: always